version: '3'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    tty: true
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql