 server:
   error:
     include-stacktrace: on-param

 spring:
   datasource:
     url: jdbc:mariadb://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
     username: root
     password: password

   jpa:
     hibernate:
       ddl-auto: update